AllCops:
  Exclude:
    - 'test/dummy/db/schema.rb'

FrozenStringLiteralComment:
  Enabled: true
Metrics/MethodLength:
  Max: 155
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Max: 150
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Enabled: false
